/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_package;

import Backend_package.Admin;
import Backend_package.AdminException;
import Backend_package.Features;
import Backend_package.Patient;
import Backend_package.User;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author C L
 */
public class AdminFrame extends javax.swing.JFrame implements PatientsView{
ArrayList<Patient> patientList=new ArrayList<>();
Patient patient=null;
Admin admin=new Admin();

/*
private String patient_ID;
    private String patientName;
    private String age;
    private String address;
    private String phone_no;
    private String Scanned_date;
    private String Appoinment;
    private String doctor_name;
    private String Blood_group;
    private String gender;
    private String imagePath;
    */
    private Features ft;
    
    public AdminFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage("project Images\\Project_Logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exit_admin = new javax.swing.JLabel();
        minimize_admin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchID = new javax.swing.JLabel();
        searchID_txt = new javax.swing.JTextField();
        searchID_btn = new javax.swing.JButton();
        extract_btn = new javax.swing.JButton();
        showFeature_btn = new javax.swing.JButton();
        test_btn = new javax.swing.JButton();
        MRIImage = new javax.swing.JLabel();
        bayesRule_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        logout_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tumor Classification");

        exit_admin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit_admin.setForeground(new java.awt.Color(255, 255, 255));
        exit_admin.setText("X");
        exit_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_adminMouseExited(evt);
            }
        });

        minimize_admin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minimize_admin.setForeground(new java.awt.Color(255, 255, 255));
        minimize_admin.setText("-");
        minimize_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_adminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimize_admin)))
                .addGap(18, 18, 18)
                .addComponent(exit_admin)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minimize_admin)
                            .addComponent(exit_admin))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        searchID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchID.setForeground(new java.awt.Color(255, 255, 255));
        searchID.setText("Patient ID");

        searchID_txt.setBackground(new java.awt.Color(44, 62, 80));
        searchID_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchID_txt.setForeground(new java.awt.Color(255, 255, 255));
        searchID_txt.setToolTipText("Patient ID");

        searchID_btn.setBackground(new java.awt.Color(34, 167, 240));
        searchID_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchID_btn.setForeground(new java.awt.Color(255, 255, 255));
        searchID_btn.setText("Search");
        searchID_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchID_btnActionPerformed(evt);
            }
        });

        extract_btn.setBackground(new java.awt.Color(34, 167, 240));
        extract_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        extract_btn.setForeground(new java.awt.Color(255, 255, 255));
        extract_btn.setText("Extract Features");
        extract_btn.setEnabled(false);
        extract_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extract_btnActionPerformed(evt);
            }
        });

        showFeature_btn.setBackground(new java.awt.Color(34, 167, 240));
        showFeature_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showFeature_btn.setForeground(new java.awt.Color(255, 255, 255));
        showFeature_btn.setText("show Features");
        showFeature_btn.setEnabled(false);
        showFeature_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFeature_btnActionPerformed(evt);
            }
        });

        test_btn.setBackground(new java.awt.Color(34, 167, 240));
        test_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test_btn.setForeground(new java.awt.Color(255, 255, 255));
        test_btn.setText("Show Result");
        test_btn.setEnabled(false);
        test_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_btnActionPerformed(evt);
            }
        });

        MRIImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\C L\\Documents\\NetBeansProjects\\MRIProject\\project Images\\picture_icon.png")); // NOI18N

        bayesRule_btn.setBackground(new java.awt.Color(34, 167, 240));
        bayesRule_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bayesRule_btn.setForeground(new java.awt.Color(255, 255, 255));
        bayesRule_btn.setText("Calculate Accuracy");
        bayesRule_btn.setEnabled(false);
        bayesRule_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayesRule_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addComponent(searchID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(searchID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchID_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(MRIImage, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(showFeature_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(test_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bayesRule_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(extract_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchID)
                    .addComponent(searchID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchID_btn))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(extract_btn)
                        .addGap(18, 18, 18)
                        .addComponent(showFeature_btn)
                        .addGap(18, 18, 18)
                        .addComponent(test_btn)
                        .addGap(18, 18, 18)
                        .addComponent(bayesRule_btn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(MRIImage, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        logout_btn.setBackground(new java.awt.Color(244, 67, 54));
        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(logout_btn)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_adminMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_adminMouseClicked

    private void exit_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_adminMouseEntered
        // TODO add your handling code here:
        exit_admin.setForeground(new java.awt.Color(244,67,54));
    }//GEN-LAST:event_exit_adminMouseEntered

    private void exit_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_adminMouseExited
        // TODO add your handling code here:
        exit_admin.setForeground(Color.white);
    }//GEN-LAST:event_exit_adminMouseExited

    private void minimize_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_adminMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_adminMouseClicked

    private void searchID_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchID_btnActionPerformed
        // TODO add your handling code here:
        try{
            CheckEcxeption();
            PatientsPresnter presnter=new PatientsPresnter(this);
            presnter.getPatientList();
            /*
            File f=new File("Project Files\\Patient.txt");
            FileReader reader=new FileReader(f);
            BufferedReader bf=new BufferedReader(reader);
            String line=null;
            String[] ListOfLines = null;
            while((line= bf.readLine()) != null){
                ListOfLines=line.split("@");
                patient_ID=ListOfLines[0];
                patientName=ListOfLines[1];
                age=ListOfLines[2];
                address=ListOfLines[3];
                phone_no=ListOfLines[4];
                Scanned_date=ListOfLines[5];
                Appoinment=ListOfLines[6];
                doctor_name=ListOfLines[7];
                Blood_group=ListOfLines[8];
                gender=ListOfLines[9];
                imagePath=ListOfLines[10];
                Patient patient=new Patient(patient_ID, phone_no, Scanned_date, Appoinment, doctor_name, Blood_group, gender, imagePath, patientName, address, age);
                patientList.add(patient);

            }
            */

            String searchForID=searchID_txt.getText();
            boolean check=false;
            for(Patient p : patientList){
                if (p.getPatient_ID().equals(searchForID)){
                    patient=p;
                    check=true;
                    break;
                }
            }
            if(check){
                extract_btn.setEnabled(true);
                
                ImageIcon icon=new ImageIcon(patient.getImagePath());
                Image img=icon.getImage();
                Image imgScale=img.getScaledInstance(285, 285, Image.SCALE_SMOOTH);
                icon=new ImageIcon(imgScale);
                MRIImage.setIcon(icon);
            }
            else{
                extract_btn.setEnabled(false);
                showFeature_btn.setEnabled(false);
                test_btn.setEnabled(false);
                bayesRule_btn.setEnabled(false);
                
                ImageIcon icon=new ImageIcon("project Images\\picture_icon.png");
                MRIImage.setIcon(icon);
                throw new AdminException("This ID is not exist");
            }
        }
        catch(AdminException ee){
            new WrongDialog_Admin(ee.getMessage()).setVisible(true);
        }
    }//GEN-LAST:event_searchID_btnActionPerformed

    private void extract_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extract_btnActionPerformed
    // TODO add your handling code here:
    new DoneFrame().setVisible(true);
    admin.extract(patient.getImagePath());
    ft=admin.getImage();
    
    showFeature_btn.setEnabled(true);
    test_btn.setEnabled(true);
    bayesRule_btn.setEnabled(true);
    }//GEN-LAST:event_extract_btnActionPerformed

    private void showFeature_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFeature_btnActionPerformed
        // TODO add your handling code here:
        new FeaturesFrame(ft, patient.getPatient_ID()).setVisible(true);
    }//GEN-LAST:event_showFeature_btnActionPerformed

    private void test_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_btnActionPerformed
        // TODO add your handling code here:
        String status =admin.test(ft);
        new PatientStatusFrame(status).setVisible(true);
    }//GEN-LAST:event_test_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        new SignInFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void bayesRule_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayesRule_btnActionPerformed
        // TODO add your handling code here:
        //BayesRule calcAccuracy=new BayesRule();
        String accuracy= admin.Apply_classifier();
        new AccuracyFrame(accuracy).setVisible(true);
    }//GEN-LAST:event_bayesRule_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MRIImage;
    private javax.swing.JButton bayesRule_btn;
    private javax.swing.JLabel exit_admin;
    private javax.swing.JButton extract_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel minimize_admin;
    private javax.swing.JLabel searchID;
    private javax.swing.JButton searchID_btn;
    private javax.swing.JTextField searchID_txt;
    private javax.swing.JButton showFeature_btn;
    private javax.swing.JButton test_btn;
    // End of variables declaration//GEN-END:variables

    private void CheckEcxeption() throws AdminException {
        if(searchID_txt.getText().isEmpty())
            throw new AdminException("Please enter patient ID");
    }

    @Override
    public void onGetPatientsList(ArrayList<Patient> patient) {
        patientList=patient;
    }
}
